### ISSUE TITLE
Random Syntax Error 

### ISSUE THREAD

**Issue by ilkevinli** [jrhubott/homebridge-homeseer#10]
Hi,
    I have homebridge installed on my pi with the homebridge-homeseer-plugin. Every few days homebridge stops working and I see the below error. Anyone have any ideas what would cause this ? Thanks.

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-homeseer-plugin/index.js:429:35)
    at Request._callback (/usr/local/lib/node_modules/homebridge-homeseer-plugin/index.js:251:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-homeseer-plugin/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-homeseer-plugin/node_modules/request/request.js:1163:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-homes

**Comment by jvmahon** [comment]
Probably a failure accessing data from HomeSeer during status update polling. Is the polling period set to a low time period (say 10 seconds) with many devices?  If so, this plugin will poll HomeSeer quite a bit and you might be overwhelming HomeSeer with too many polls (just a guess).
